### ISSUE TITLE
installation trouble shooting

### ISSUE THREAD

**Issue by maxko37** [sms77io/python-client#1]
Hello,

first of all thank you for the code. Unfortunately I am not able to install the package. If I am doing it as you recommend (with pip3 install sms77api) the package/folder which gets installed is empty. Can you give any advice?
Thanks!

**Comment by matthiez** [comment]
Hi,

[v1.1.0](https://pypi.org/manage/project/sms77api/release/1.1.0/) just got released. Please try again now and have a look at the updated README.

**Comment by maxko37** [comment]
Hi matthiez,

works perfectly now. I also erased the 'src.' part but I didn't adjust the import.
Thanks for your help!
